config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    get 'application/index'

    resources :users, only: [:index]
    resources :eventos, only: [:index]
    resources :promos, only: [:index]
    resources :empresas, only: [:index]
    resources :puntos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root 'info#index'
  get 'info/index'
  get 'info/mercadillo'
  get 'info/historia'
  get 'info/turismoactivo'
  get 'info/turismo'
  get 'info/alojamiento'
  get 'info/gastronomia'
  get 'info/naturaleza'
  get 'info/ocio'
  get 'info/mapa'
  get '/mispromos', to: 'promos#mispromos'

  resources :puntos
  resources :eventos
  resources :empresas
  resources :promos

  devise_for :users

end

app/models/punto.rb
class Punto < ApplicationRecord
  has_one_attached :image


end

app/controllers/admin/puntos_controller.rb
class Admin::PuntosController < ApplicationController
    before_action :set_punto, only: [:show, :edit, :update, :destroy]

    # GET /puntos
    # GET /puntos.json
    def index
      @puntos = Punto.all
    end

    # GET /puntos/1
    # GET /puntos/1.json
    def show
    end

    # GET /puntos/new
    def new
      @punto = Punto.new
    end

    # GET /puntos/1/edit
    def edit
    end

    # POST /puntos
    # POST /puntos.json
    def create
      @punto = Punto.new(punto_params)

      respond_to do |format|
        if @punto.save
          format.html { redirect_to @punto, notice: 'Punto was successfully created.' }
          format.json { render :show, status: :created, location: @punto }
        else
          format.html { render :new }
          format.json { render json: @punto.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /puntos/1
    # PATCH/PUT /puntos/1.json
    def update
      respond_to do |format|
        if @punto.update(punto_params)
          format.html { redirect_to @punto, notice: 'Punto was successfully updated.' }
          format.json { render :show, status: :ok, location: @punto }
        else
          format.html { render :edit }
          format.json { render json: @punto.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /puntos/1
    # DELETE /puntos/1.json
    def destroy
      @punto.destroy
      respond_to do |format|
        format.html { redirect_to puntos_url, notice: 'Punto was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_punto
        @punto = Punto.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def punto_params
        params.require(:punto).permit(:titulo, :subtitulo, :descripcion, :lat, :lon, :horario, :precio, :info, :video, :image)
      end
  end

app/controllers/puntos_controller.rb
class PuntosController < ApplicationController
  before_action :set_punto, only: [:show, :edit, :update, :destroy]

  # GET /puntos
  # GET /puntos.json
  def index
    @puntos = Punto.all
  end

  # GET /puntos/1
  # GET /puntos/1.json
  def show
  end

  # GET /puntos/new
  def new
    @punto = Punto.new
  end

  # GET /puntos/1/edit
  def edit
  end

  # POST /puntos
  # POST /puntos.json
  def create
    @punto = Punto.new(punto_params)

    respond_to do |format|
      if @punto.save
        format.html { redirect_to @punto, notice: 'Punto was successfully created.' }
        format.json { render :show, status: :created, location: @punto }
      else
        format.html { render :new }
        format.json { render json: @punto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puntos/1
  # PATCH/PUT /puntos/1.json
  def update
    respond_to do |format|
      if @punto.update(punto_params)
        format.html { redirect_to @punto, notice: 'Punto was successfully updated.' }
        format.json { render :show, status: :ok, location: @punto }
      else
        format.html { render :edit }
        format.json { render json: @punto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puntos/1
  # DELETE /puntos/1.json
  def destroy
    @punto.destroy
    respond_to do |format|
      format.html { redirect_to puntos_url, notice: 'Punto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punto
      @punto = Punto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def punto_params
      params.require(:punto).permit(:titulo, :subtitulo, :descripcion, :lat, :lon, :horario, :precio, :info, :video, :image)
    end
end

app/helpers/admin/puntos_helper.rb
module Admin::PuntosHelper
end

app/helpers/puntos_helper.rb
module PuntosHelper
end

app/views/admin/puntos/_form.html.erb
<%= form_with(model: [:admin, punto], local: true) do |form| %>
  <% if punto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(punto.errors.count, "error") %> prohibited this punto from being saved:</h2>

      <ul>
      <% punto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :subtitulo %>
    <%= form.text_field :subtitulo %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lon %>
    <%= form.text_field :lon %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_field :horario %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info %>
  </div>


  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/puntos/edit.html.erb
<h1>Editing Punto</h1>

<%= render 'form', punto: @punto %>

<%= link_to 'Show', @punto %> |
<%= link_to 'Back', info_mapa_path %>

app/views/admin/puntos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Puntos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Subtitulo</th>
      <th>Descripcion</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Horario</th>
      <th>Precio</th>
      <th>Info</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puntos.each do |punto| %>
      <tr>
        <td><%= punto.titulo %></td>
        <td><%= punto.subtitulo %></td>
        <td><%= punto.descripcion %></td>
        <td><%= punto.lat %></td>
        <td><%= punto.lon %></td>
        <td><%= punto.horario %></td>
        <td><%= punto.precio %></td>
        <td><%= punto.info %></td>
        <td><%= punto.video %></td>
        <td><%= link_to 'Show', punto %></td>
        <td><%= link_to 'Edit', edit_admin_punto_path(punto) %></td>
        <td><%#= link_to 'Destroy', admin_punto_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Punto', new_admin_punto_path %>

app/views/admin/puntos/new.html.erb
<h1>New Punto</h1>

<%= render 'form', punto: @punto %>

<%= link_to 'Back', info_mapa_path %>

app/views/admin/puntos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @punto.titulo %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @punto.subtitulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @punto.descripcion %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @punto.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @punto.lon %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @punto.horario %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @punto.precio %>
</p>

<p>
  <strong>Info:</strong>
  <%= @punto.info %>
</p>

<p>
  <strong>Video:</strong>
  <%= @punto.video %>
</p>

<%= link_to 'Edit', edit_punto_path(@punto) %> |
<%= link_to 'Back', puntos_path %>