config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    get 'application/index'

    resources :users, only: [:index]
    resources :eventos, only: [:index]
    resources :promos, only: [:index]
    resources :empresas, only: [:index]
    resources :puntos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root 'info#index'
  get 'info/index'
  get 'info/mercadillo'
  get 'info/historia'
  get 'info/turismoactivo'
  get 'info/turismo'
  get 'info/alojamiento'
  get 'info/gastronomia'
  get 'info/naturaleza'
  get 'info/ocio'
  get 'info/mapa'
  get '/mispromos', to: 'promos#mispromos'

  resources :puntos
  resources :eventos
  resources :empresas
  resources :promos

  devise_for :users

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  def index
    @users = User.count
    @promos = Promo.count
    @eventos = Evento.count
    @empresas = Empresa.count
    @puntos = Punto.count
  end

  private
  def authorize_admin!
    authenticate_user!
    unless (current_user.admin?)
      redirect_to root_path, alert: "Tú no eres administrador."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end

  def admins_only(&block)
    block.call if (current_user.try(:admin?) || current_user.try(:superadmin?))
  end

  def avatar_url(user)
    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

  def time_format_mini(datetime)
    I18n.l(datetime, format: '%A') + datetime.strftime(", %d %b %Y %H:%M")
  end

  def time_format_mini_mini(datetime)
    datetime.strftime("%d %b %Y %H:%M")
  end

  def full_title(page_title = "")
    default_title = "Guia #{$current_city} - Turismo y Empresas"
    if page_title.empty?
      default_title
    else
      "#{page_title} | #{default_title}"
    end
  end



end

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-sm-3 admin">
    <div class="admin-sidebar">
      <div class="user-panel">
        <span class="pull-left image">
          <span><%= image_tag avatar_url(current_user), width:30, class: "img-circle" %></span>
        </span>
        <div class="float-right panel-color"><%= current_user.email %></div>
      </div>

    </div>
    <ul class="admin-menu">
      <li class="text-uppercase text-center header">Main Navigation</li>
      <li>
        <%= link_to admin_users_path do %>
          <%= fa_icon "users" %>
          <span class="badge badge-secondary">Usuarios</span>
          <span class="badge badge-primary float-right"><%= @users %></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_empresas_path do %>
          <%= fa_icon "building" %>
          <span class="badge badge-secondary">Empresas</span>
          <span class="badge badge-primary float-right"><%= @empresas %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_promos_path do %>
          <%= fa_icon "bullhorn" %>
          <span class="badge badge-secondary">Promociones</span>
          <span class="badge badge-primary float-right"><%= @promos %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_eventos_path do %>
          <%= fa_icon "globe" %>
          <span class="badge badge-secondary">Eventos</span>
          <span class="badge badge-primary float-right"><%= @eventos %></span>
        <% end %>
      </li>

      <li>
        <%= link_to admin_puntos_path do %>
          <%= fa_icon "globe" %>
          <span class="badge badge-secondary">Puntos</span>
          <span class="badge badge-primary float-right"><%= @puntos %></span>
        <% end %>
      </li>
<p>
    </ul>
  </div>
  <div class="col-sm-9">
    <header>
      <h1 class="text-center">Administración</h1>
      <h4 class="text-center">Panel de control</h4>
    </header>
  </div>
</div>