config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'application#index'
    get 'application/index'

    resources :users, only: [:index]
    resources :eventos, only: [:index]
    resources :promos, only: [:index]
    resources :empresas, only: [:index]
    resources :puntos, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root 'info#index'
  get 'info/index'
  get 'info/mercadillo'
  get 'info/historia'
  get 'info/turismoactivo'
  get 'info/turismo'
  get 'info/alojamiento'
  get 'info/gastronomia'
  get 'info/naturaleza'
  get 'info/ocio'
  get 'info/mapa'
  get '/mispromos', to: 'promos#mispromos'

  resources :puntos
  resources :eventos
  resources :empresas
  resources :promos

  devise_for :users

end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :empresa
  has_one_attached :image

  private
  def promo_params
    params.require(:promo).permit(:titulo, :info, :fecha, :image)
  end
end

app/controllers/admin/promos_controller.rb
class Admin::PromosController < ApplicationController
  def index
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  def mispromos
  plan = current_user.empresa.plan
  last_promo = current_user.empresa.try(:promos).try(:last)

  if plan != 'premium'
    if last_promo != nil
      waiting = waiting_date(last_promo, plan)
      if (waiting > Time.zone.now)
        @waiting = (waiting - Time.zone.now).to_i
      end
    else
      @waiting = nil
    end
  end

  @pasadas = Promo.where("validez <= ? AND empresa_id = ?", Time.zone.now, current_user.empresa.id).order("created_at DESC")
  @actuales = Promo.where("validez > ? AND empresa_id = ?", Time.zone.now, current_user.empresa.id).order("created_at DESC")

  @ready = false
  case plan
  when 'premium'
    if (@actuales.count < 3)
      return @ready = true
    else
      if is_still_valid?(@actuales[0]) == false
        return @ready = true # At least the last one isn' valid
      else
        @waiting = @actuales[0].validez.to_i - Time.zone.now.to_i
        flash.now[:notice] = "Has llegado al límite máximo (3) de promociones simultáneas"
      end
    end
  when 'plus'
    return @ready = true if @waiting == nil
  when 'basic'
    return @ready = true if @waiting == nil
  end

end

  # POST /promos
  # POST /promos.json
  def create
    user ||= current_user
    @promo = user.try(:empresa).try(:promos).build(promo_params)
    set_validez
    
    plan = current_user.empresa.plan
    #last_promo = current_user.empresa.try(:promos).try(:last).try(:created_at)
    #last_promo_when = helpers.time_format_mini(last_promo) if last_promo.nil? == false

    if (plan == 'noplan')
      flash[:error] = "No puedas lanzar promociones. Tu plan está fuera de validez. Renuévalo."
      redirect_to root_path
    else
      create_promo
    end

  end
  ######################

  def create_promo
        #===========> Remember the promos are odered inversely so I take first (more recent one)
          valid_value = false
          last_promo = current_user.empresa.try(:promos).try(:last).try(:created_at)
          plan = current_user.empresa.plan
          #nil??? primera vez??
            if (1==2)

            else
              if last_promo == nil #no previous publication
                valid_value = true
                set_validez
              else
                if (plan == 'premium')
                  last_promos = current_user.empresa.try(:promos).try(:last, 3)
                  if last_promos.count < 3
                    valid_value = true
                    set_validez
                  else
                    # It has 3 or more
                    if is_still_valid?(last_promos[2]) # last and oldest element
                      #All 3 options active, must wait until at least 1 finish validity
                      flash.now[:error] = "Tienes 3 promociones en activo (Máximo). Cuando acabe una podrás poner más."
                      render 'new' and return
                    else
                      # We know not all 3 options are active, so we can activate a new one
                      valid_value = true
                      set_validez
                    end
                  end
                else
                  #basic/plus
                  last_promo_item = current_user.empresa.try(:promos).try(:first)
                  if is_still_valid?(last_promo_item)
                    flash.now[:error] = "Tu última publicación aún está activa (pásate a premium si quieres varias y sin esperas)"
                    render 'new' and return
                  else
                    #Has finished the waiting period?
                    @waiting_until = waiting_date(last_promo_item, plan)
                    if (Time.zone.now > @waiting_until)
                      valid_value = true
                      set_validez
                    else
                      flash.now[:error] = "Aún tienes que esperar hasta la próxima promoción (pásate a premium si no quieres esperas)"
                      render 'new' and return
                    end
                  end

                  end
                end
            end

      # Ya tenemos todo para saber si es válido o no
          if valid_value == true
              respond_to do |format|
                if @promo.save

                  format.html { redirect_to @promo, notice: 'La promoción se ha creado con éxito' }
                  format.json { render :show, status: :created, location: @promo }
                else
                  format.html { render :new, alert: @promo.errors }
                  format.json { render json: @promo.errors, status: :unprocessable_entity }
                end
              end
          else
            flash.now[:error] = "Debes seleccionar al menos una opción."
            render 'new' and return
          end

          rescue ActiveRecord::RecordInvalid => e
            flash[:error] = e
            redirect_to '/promos/new'
            #===========> Final
      end

##################################


  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    def set_validez

      case params[:promo][:validez]
      when 'alta'
        @promo.validez = Time.zone.now + 7.days
      when 'media'
        @promo.validez = Time.zone.now + 3.days
      when 'baja'
        @promo.validez = Time.zone.now + 1.day
      end
    end

    def is_still_valid?(promo)
      if promo.validez <= Time.zone.now
        false
      else
        true
      end
    end

    #returns the date to wait to in plans plus and basic given the last promo
    def waiting_date (last_promo_item, plan)
      num = ((last_promo_item.validez - last_promo_item.created_at)/60/60/24).round
      case num
      when 7
        if (plan == 'plus')
          last_promo_item.validez + 3.days
        elsif (plan == 'basic')
          last_promo_item.validez + 10.days
        end
      when 3
        if (plan == 'plus')
          last_promo_item.validez + 2.days
        elsif (plan == 'basic')
          last_promo_item.validez + 5.days
        end
      when 1
        if (plan == 'plus')
          last_promo_item.validez + 1.days
        elsif (plan == 'basic')
          last_promo_item.validez + 2.days
        end
      else
        #Error -> Promo lasted and unselectable number of days
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:titulo, :texto, :validez, :image)
    end
end

app/helpers/admin/promos_helper.rb
module Admin::PromosHelper
end

app/helpers/promos_helper.rb
module PromosHelper

  def time_format(datetime)
   if (datetime-Time.now) > 0
     "Aún tienes " + distance_of_time_in_words_to_now(datetime)
   else
     "La promoción ha terminado"
   end
 end

end

app/views/promos/_form.html.erb
<%= form_with(model: promo, local: true) do |form| %>
  <% if promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% promo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :texto %>
    <%= form.text_area :texto %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="form-group">
        <p>
      Duración de la promoción:</br>
              <%= form.radio_button :validez, "baja" %>
              <%= form.label 'validez_baja', ' 24 horas' %>

              <%= form.radio_button :validez, "media" %>
              <%= form.label 'validez_media', ' 3 días' %>

              <%= form.radio_button :validez, "alta" %>
              <%= form.label 'validez_alta', ' 1 semana' %>

        </p>
  </div>



  <div class="actions">
    <%= form.submit "Publicar", class: "btn btn-primary" %>
  </div>
<% end %>


<!--  -->

app/views/promos/_promo.html.erb
<%= link_to promo_path(promo) do %>
  <div class="alert alert-success">
    <h6 class="alert-link">  <%= promo.titulo %>  </h6>
    <small class="text-right text-muted"><%= promo.empresa.nombre if (promo.empresa) %></small>
    <small><%= Nokogiri::HTML(promo.texto).text.truncate(100, separator: ' ') %> </small>
    <p><h6> <strong> <%= time_format(promo.validez) %> </strong></h6></p>

    <%if promo.image.attached?%>
      <%= image_tag promo.image, class: "img-fluid img-thumbnail fotos"%>
    <% end %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<h1>Promos</h1>

<div class="col-md-12">

  <div class="alert alert-info">
    <strong>OFERTAS FLASH</strong>
  </div>


  <% if @promos.any?  %>
    <div class="card-columns">

      <% @promos.each do |promo| %>
      <div class="card">
        <%= link_to promo_path(promo) do %>
          <div class="alert alert-success">
            <h6 class="alert-link">  <%= promo.titulo %>  </h6>
            <small class="text-right text-muted"><%= promo.empresa.nombre if (promo.empresa) %></small>
            <small><%= Nokogiri::HTML(promo.texto).text.truncate(100, separator: ' ') %> </small>
            <p><h6> <strong> <%= time_format(promo.validez) %> </strong></h6></p>

            <%if promo.image.attached?%>
              <%= image_tag promo.image, class: "img-fluid img-thumbnail fotos"%>
            <% end %>
          </div>
        <% end %>
      </div>
      <% end %>

    </div>
  <% else %>
    <div class="alert alert-secondary">
      No hay promociones recientes
    </div>
  <% end %>
  <div class="row">
    <div class="col-12">
      <div class="text-right">
        <%= link_to 'Ver todas', promos_path %>
      </div>
    </div>
  </div>

</div>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Texto</th>
      <th>Validez</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promos.each do |promo| %>
      <tr>
        <td><%= promo.titulo %></td>
        <td><%= promo.texto %></td>
        <td><%= promo.validez %></td>
        <td><%= link_to 'Show', promo %></td>
        <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
        <td><%= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/mispromos.html.erb
<%= hidden_field_tag 'plan', current_user.empresa.plan %>
<%= hidden_field_tag 'waiting', @waiting %>


<div class="row">
  <div class="col-md-3">
    <p><h2 class="text-center">Disponibilidad</h2></p>

    <% if @ready == true %>
      <p class="text-center">¡Listo!</p>
      <p><h2 class="text-muted text-center"></h2></p>
      <ul class="list-unstyled"><p><li><%= link_to "Nueva promoción", new_promo_path, class: "btn btn-primary d-block mx-auto" %></li></p></ul>
    <% else %>

      <ul class="list-unstyled"> <p><li><%= link_to "Nueva promoción", new_promo_path, class: "btn btn-primary disabled d-block mx-auto" %></li></p> </ul>
      <p class="text-center"><small>Aún tienes que esperar</small></p>
      <p class="text-center"><span id="time"></span></p>

      <div id="clockdiv" class="mx-autdo d-block">
        <div>
          <span class="days"></span>
          <div class="smalltext">Días</div>
        </div>
        <div>
          <span class="hours"></span>
          <div class="smalltext">Horas</div>
        </div>
        <div>
          <span class="minutes"></span>
          <div class="smalltext">Minutos</div>
        </div>
        <div>
          <span class="seconds"></span>
          <div class="smalltext">Segundos</div>
        </div>
      </div>


      <p class="text-center"><small>hasta la próxima promoción</small></p>

    <% end %>

    <div id="nopremium">
      <p> <div class="text-muted text-center">¿No te gusta esperar?</div></p>
      <p class="text-center"><%= link_to "Pásate a Premium", "/precios"%></p>
    </div>

    <%#= link_to "Obtener créditos", consiguemascreditos_path, class: "btn btn-success d-block mx-auto" %>

  </div>
  <div class="col-md-9">
    <p><h2 class="text-center">Promociones en activo</h2></p>

    <% if @actuales.any?  %>
      <%= render @actuales %>
    <% else %>
      <div class="row text-center text-muted">
        <div class="col-md-12">
          <h6 class="text-center">No hay promociones en activo</h6>
        </div>
      </div>
    <% end %>


    <p><h2 class="text-center">Promociones pasadas</h2></p>

    <% if @pasadas.any?  %>
      <%= render @pasadas %>
    <% else %>
      <div class="row text-muted">
        <div class="col-md-12">
          <h6 class="text-center">Aún no hay promociones inactivas</h6>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/promos/new.html.erb
<h1>New Promo</h1>

<%= render 'form', promo: @promo %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p><h2 class="text-center">Enséñale esto al comerciante para obtener tu descuento</h2></p>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-9">

      <% if @promo.empresa.try(:present?) %>
        <% if @promo.empresa.logo.attached? %>
          <%= link_to(image_tag(@promo.empresa.logo, class: "img-fluid"), empresa_path(@promo.empresa)) %>
        <% else %>
          <%= @promo.empresa.nombre %>
        <% end %>
      <% end %>
      <p><h1><strong><%= @promo.titulo %></strong></h1></p>
    </div>


    <div class="col-md-3">
      <img src="https://chart.googleapis.com/chart?cht=qr&chl=<%=  %><%= request.fullpath %>&chs=160x160&chld=L|0" class="qr-code img-thumbnail img-responsive mx-auto d-block">
      <p class="text-center">
        <% if (Time.now > @promo.validez) %>
          <span class="badge badge-danger still">
            <%= time_format(@promo.validez) %>
          </span>
        <% else %>
          <span class="badge badge-success still">
            <%= time_format(@promo.validez) %>
          </span><br/>
          <small>Fin: <%= time_format_mini(@promo.validez) %></small>

        <% end %>
      </p>
    </div>
  </div>

    <p class="lead cards"><%= @promo.texto %></p>

    <hr class="my-4">
    <div class="row">
      <div class="col-md-6">

      </div>


    </div>
    <div class="col-12">
      <% if @promo.image.attached? %>
      <div class="img-fluid">
        <%= image_tag @promo.image, class: "img-fluid mx-auto d-block" %>
      </div>
      <% end %>
    </div>


</div>

<%= link_to "Volver", promos_path %>